server:
  port: 8081
spring:
  application:
    name: dragon-demo
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public