server:
  port: 8080
spring:
  application:
    name: dragon-core
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public