spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: 127.0.0.1
    username: dragon
    password: dragon
    virtualHost: dragon
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8858
machine:
  dragon:
    system:
      datasource:
        url: jdbc:mysql://127.0.0.1:3306/dragon_system?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: root

feign:
  sentinel:
    enable: true

knife4j:
  # 开启生产环境屏蔽
  production: false

logging:
  level:
    com.machine.dragon: debug
    com.baomidou.mybatisplus.samples: debug